#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Desnowy

# Short bio or description (displayed in the header)
description: Normal people from Zhai

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/sakaman/sakaman.github.io/master/images/logo@1024px.png
avatar: /assets/logo@1024px.png

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logo@16px.png'
  32: '/assets/logo@32px.png'
  96: '/assets/logo@96px.png'
  120: '/assets/logo@120px.png'
  144: '/assets/logo@144px.png'
  180: '/assets/logo@180px.png'
  512: '/assets/logo@512px.png'
  1024: '/assets/logo@1024px.png'

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: sakaman/sakaman.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: sakaman

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://sakaman.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "https://sakaman.github.io"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# permalink: /:categories/:title/
permalink: pretty

# The release of Jekyll Now that you're using
version: v1.2.0

# markdown: kramdown
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  # syntax_highlighter: coderay
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  # style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji
  - jekyll-paginate
  - kramdown-syntax-coderay
  - github-pages
  - jekyll-toc

# theme: jekyll-theme-so-simple
# remote_theme: "mmistakes/so-simple-theme@3.2.0

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji
  - jekyll-paginate
  - kramdown-syntax-coderay
  - github-pages
  - jekyll-toc

paginate: 10
paginate_path: blog/page:num

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

defaults:
  - scope:
      path: ""
    values:
      toc: true