name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '2.7'
        
    - run: bundle install && bundle exec jekyll build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _site
        force_orphan: true
